/** Stick kits — AvA series looks + publicly described Animation VERSUS archetypes. */

export const CHARACTERS = {
  orange: {
    id: "orange",
    name: "ORANGE",
    subtitle: "The All-Rounder",
    // The Second Coming: hollow orange head
    color: "#ff7a2f",
    outline: "#ff7a2f",
    hollowHead: true,
    pencil: true,
    maxHp: 110,
    nodes: 4,
    speed: 2.0,
    jump: 13.5,
    airJumps: 1,
    weight: 1,
    desc: "Pencil props, martial arts, rotating projectiles.",
    projectileCycle: ["shuriken", "anvil", "rocket"],
    moves: {
      nSpecial: "Pencil Toss (Shuriken → Anvil → Rocket)",
      uSpecial: "Drawn Hammer (Overhead)",
      dSpecial: "Sketch Slide",
      fSpecial: "Prop Rush",
      bSpecial: "Eraser Bash",
    },
  },
  red: {
    id: "red",
    name: "RED",
    subtitle: "Up-Close Cheetah",
    color: "#e23b3b",
    outline: "#8a1515",
    hollowHead: false,
    headband: true,
    maxHp: 110,
    nodes: 4,
    speed: 2.4,
    jump: 13.2,
    airJumps: 1,
    weight: 0.92,
    desc: "Fastest rushdown. Animal-spirit martial arts.",
    moves: {
      nSpecial: "Cheetah Rush",
      uSpecial: "Tiger Upper",
      dSpecial: "Wolf Sweep",
      fSpecial: "Beast Fist",
      bSpecial: "Spirit Counter",
    },
  },
  blue: {
    id: "blue",
    name: "BLUE",
    subtitle: "Master of Surprise",
    color: "#3a7cff",
    outline: "#143a7a",
    hollowHead: false,
    maxHp: 110,
    nodes: 4,
    speed: 1.95,
    jump: 13.8,
    airJumps: 1,
    weight: 1,
    desc: "Potions, mist, portals, breakdance mixups.",
    moves: {
      nSpecial: "Potion Toss",
      uSpecial: "Portal Swap",
      dSpecial: "Mist Bomb",
      fSpecial: "Breakdance Kick",
      bSpecial: "Capoeira Spin",
    },
  },
  green: {
    id: "green",
    name: "GREEN",
    subtitle: "Mid-Range Threat",
    color: "#2bbf7a",
    outline: "#0d5a38",
    hollowHead: false,
    fishingRod: true,
    maxHp: 110,
    nodes: 4,
    speed: 1.9,
    jump: 13.0,
    airJumps: 1,
    weight: 1.05,
    desc: "全画面钩索：勾中后可移动；拉回敌人会跟上；拉回时按攻击起飞；暴击/Danger秒杀；CD 5秒。",
    moves: {
      nSpecial: "Cast & Hook（面朝全场钩索）",
      uSpecial: "Zipline Reel",
      dSpecial: "Power Chord",
      fSpecial: "Cast & Hook",
      bSpecial: "Rod Whip",
    },
  },
  yellow: {
    id: "yellow",
    name: "YELLOW",
    subtitle: "Long-Range Coder",
    color: "#f0c419",
    outline: "#8a6a08",
    hollowHead: false,
    laptop: true,
    maxHp: 110,
    nodes: 4,
    speed: 1.8,
    jump: 12.8,
    airJumps: 1,
    weight: 0.95,
    desc: "Laptop code projectiles, pop-up, warp teleport.",
    moves: {
      nSpecial: "Compile Shot",
      uSpecial: "Stack Overflow Pop",
      dSpecial: "Debug Warp",
      fSpecial: "Packet Spam",
      bSpecial: "Hard Reset Warp",
    },
  },
  purple: {
    id: "purple",
    name: "PURPLE",
    subtitle: "Flyer and Soarer",
    color: "#9b4dff",
    outline: "#4a1a8a",
    hollowHead: false,
    wings: true,
    maxHp: 110,
    nodes: 4,
    speed: 2.1,
    jump: 14.2,
    airJumps: 2,
    weight: 0.9,
    desc: "Elytra wings, glide, aerial combos, dive.",
    moves: {
      nSpecial: "Wing Slash",
      uSpecial: "Soar Spike",
      dSpecial: "Meteor Dive",
      fSpecial: "Air Drill",
      bSpecial: "Ground Snap Teleport",
    },
  },
  // Story Mode boss only — not in free character select
  versus: {
    id: "versus",
    name: "VERSUS",
    subtitle: "Corrupted Engine",
    color: "#3a3a48",
    outline: "#9aa3b2",
    hollowHead: true,
    pencil: false,
    maxHp: 140,
    nodes: 5,
    speed: 2.15,
    jump: 13.8,
    airJumps: 1,
    weight: 1.05,
    desc: "Story boss: cracked VS engine wearing a stick-shaped shell.",
    projectileCycle: ["shuriken", "anvil", "rocket"],
    moves: {
      nSpecial: "Rule Inject",
      uSpecial: "Undo Spike",
      dSpecial: "Loop Slide",
      fSpecial: "Force Match",
      bSpecial: "Corrupt Bash",
    },
  },
  // Campaign: Dark Lord (all chapter finales) + red spider adds
  dark_lord: {
    id: "dark_lord",
    name: "黑暗领主",
    subtitle: "DARK LORD",
    color: "#2a1824",
    outline: "#8a2848",
    hollowHead: false,
    maxHp: 300,
    nodes: 6,
    speed: 1.6,
    jump: 12,
    airJumps: 0,
    weight: 1.35,
    boss: true,
    desc: "定点巨型 Boss。弱点攻击；半血狂暴。章别技能不同。",
    moves: {
      nSpecial: "暗袭 / 数据刃",
      uSpecial: "坠暗重拳",
      dSpecial: "数据地刺",
      fSpecial: "暗袭 / 数据刃",
      bSpecial: "暗影横扫",
    },
  },
  red_spider: {
    id: "red_spider",
    name: "红蜘蛛",
    subtitle: "Minion",
    color: "#d02028",
    outline: "#601018",
    hollowHead: false,
    maxHp: 22,
    nodes: 2,
    speed: 2.7,
    jump: 11,
    airJumps: 0,
    weight: 0.7,
    desc: "第一章黑暗领主召唤的红蜘蛛。",
    moves: {
      nSpecial: "扑咬",
      uSpecial: "弹跳",
      dSpecial: "低扫",
      fSpecial: "扑咬",
      bSpecial: "后跃",
    },
  },
};

export const CHARACTER_ORDER = ["orange", "red", "blue", "green", "yellow", "purple"];
export const BOSS_IDS = ["versus", "dark_lord"];
